name: Update Banklogs
on:
  workflow_dispatch:
    # Allow manual trigger
  schedule:
    # Run daily at a random time
    - cron: '49 14 * * *'
jobs:
  update-banklogs:
    runs-on: ubuntu-latest
    permissions:
      # Give API toke the ability to push commits
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch and unzip logs
        run: |
          curl https://patrickjohnston.org/ziplogs.php -o banklogs.zip
          unzip -ao banklogs.zip \*.asm
      - name: Fetch additional files
        run: |
          for f in "RAM map.asm" "SRAM map.asm" "VRAM map.asm" "Enemy RAM.asm"; do
            curl "https://patrickjohnston.org/ASM/Lists/Super%20Metroid/${f// /%20}" -o "$f"
          done
      - name: Commit new changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update logs from website
          file_pattern: '*.asm :!*.new.asm'
          commit_author: PJBoy <gcupcakekid@gmail.com>
